from car import Car 

car1=Car("Mustang", 2024, "Red", False)
print(car1)
print(car1.model)
print(car1.year)
print(car1.color)
print(car1.for_sale)
car1.drive()
car1.stop()
print()

car2=Car("Covette", 2025, "Blue", True)
print(car2)
print(car2.model)
print(car2.year)
print(car2.color)
print(car2.for_sale)
car2.drive()
car2.stop()
print()

car3=Car("Charger", 2026, "Yellow", True)
print(car3)
print(car3.model)
print(car3.year)
print(car3.color)
print(car3.for_sale)
car3.drive()
car3.stop()
print()
